[package]
name = "ectf-hsm-rust"
version = "0.1.0"
edition = "2021"

[build-dependencies]
serde_json = "1"

[dependencies]
embassy-executor = { version = "0.5", features = ["arch-cortex-m", "executor-thread"] }
embassy-time = { version = "0.3" }
embassy-sync = { version = "0.5" }

cortex-m = { version = "0.7" }
cortex-m-rt = { version = "0.7", features = ["device"] }
panic-halt = { version = "0.2" }

blake3 = { version = "1.5", default-features = false, features = ["pure"] }

[target.'cfg(not(target_arch = "arm"))'.dependencies]
pqcrypto-dilithium = "0.5"
pqcrypto-traits = "0.3"
getrandom = { version = "0.3" }

[features]
default = []

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
